version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          command: node --version1
          name: Test command
